export const REPORTS = {
   AUDIT : {
        "tableconfig" : {"name":"Audit Details","title":"AUDIT Details","download": true,"search":true,"showentries":true,"currentpage": false,
        "refresh":true,"showingentries":true,"sorting": true,"pagination":true,"add":false,"colsearch":false,"excelcond":true,"settings":true},
        "config" : [
          {"type": "date", "customFormat":true,"format": 'dd-MM-yyyy ',"title":"Date","tbody":"cdate","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Time","tbody":"ctime","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Message","tbody":"msg","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Type","tbody":"type","width":"10","filter" : true,"export":true},          
          {"dhide":true,"type":"db","title":"Record","tbody":"record_type","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Server","tbody":"server_name","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Level","tbody":"deamon_id","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Command","tbody":"	cmd","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"ARCH","tbody":"arch","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"SYSCALL","tbody":"syscall","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"SUCCESS","tbody":"success","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Exit Code","tbody":"exit_code","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"A0","tbody":"a0","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"A1","tbody":"a1","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"A2","tbody":"a2","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"A3","tbody":"a3","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Items","tbody":"items","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"PPID","tbody":"ppid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"PID","tbody":"pid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"AUID","tbody":"auid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"UID","tbody":"uid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"GID","tbody":"gid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Euid","tbody":"euid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"msg","tbody":"msg","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Suid","tbody":"suid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"fsuid","tbody":"fsuid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"egid","tbody":"egid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"sgid","tbody":"sgid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"fsgid","tbody":"fsgid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"tty","tbody":"tty","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"ses","tbody":"ses","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"comm","tbody":"comm","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"exe","tbody":"exe","width":"10","filter" : true,"export":true},          
          {"dhide":true,"type":"db","title":"key_file","tbody":"key_file","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"item","tbody":"item","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"name","tbody":"name","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"inode","tbody":"inode","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"dev","tbody":"dev","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"mode","tbody":"mode","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"ouid","tbody":"ouid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"ogid","tbody":"ogid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"rdev","tbody":"rdev","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"objtype","tbody":"objtype","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"cap_fp","tbody":"cap_fp","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"cap_fi","tbody":"cap_fi","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"cap_fe","tbody":"cap_fe","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"cap_fver","tbody":"cap_fver","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"grantors","tbody":"grantors","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"acct","tbody":"acct","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"hostname","tbody":"hostname","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"addr","tbody":"addr","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"terminal","tbody":"terminal","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"res","tbody":"res","width":"10","filter" : true,"export":true},

        ],
    },
    DNS : {
        "tableconfig" : {"name":"DNS Details","title":"DNS Details","download": true,"search":true,"showentries":true,"currentpage": false,
        "refresh":true,"showingentries":true,"sorting": true,"pagination":true,"add":false,"colsearch":false,"excelcond":true,"settings":true},
        "config" : [
          {"type": "date", "customFormat":true,"format": 'dd-MM-yyyy ',"title":"Date","tbody":"cdate","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Time","tbody":"ctime","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Client","tbody":"client_name","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Domain","tbody":"domain_name","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Level","tbody":"qry_lvl","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Record","tbody":"record_type","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Server","tbody":"server_name","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Daemon Id","tbody":"daemon_id","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Queries","tbody":"qry_type","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"daemon","tbody":"daemon","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Client IP","tbody":"client_ip","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Client Port","tbody":"client_port","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Client Name","tbody":"client_name","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Domain IP","tbody":"domain_ip","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Remarks","tbody":"remarks","width":"10","filter" : true,"export":true},
          
        ],
      },

      CRON : {
        "tableconfig" : {"name":"CRON Details","title":"DNS Details","download": true,"search":true,"showentries":true,"currentpage": false,
        "refresh":true,"showingentries":true,"sorting": true,"pagination":true,"add":false,"colsearch":false,"excelcond":true,"settings":true},
        "config" : [
          {"type": "date", "customFormat":true,"format": 'dd-MM-yyyy ',"title":"Date","tbody":"cdate","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Time","tbody":"ctime","width":"10","filter" : true,"export":true},
          {"type":"db","title":"JOB Name","tbody":"jobname","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Server Name","tbody":"server_name","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Job","tbody":"job","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Job Type","tbody":"job_type","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"jobid","tbody":"jobid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"User","tbody":"user","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Command","tbody":"command","width":"10","filter" : true,"export":true},
          
          
        ],
      },

      MSG:{
        "tableconfig" : {"name":"Message Details","title":"DNS Details","download": true,"search":true,"showentries":true,"currentpage": false,
        "refresh":true,"showingentries":true,"sorting": true,"pagination":true,"add":false,"colsearch":false,"excelcond":true,"settings":true},
        "config" : [
          {"type": "date", "customFormat":true,"format": 'dd-MM-yyyy ',"title":"Date","tbody":"cdate","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Time","tbody":"ctime","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Server Name","tbody":"server_name","width":"10","filter" : true,"export":true},
          {"type":"db","title":"Type","tbody":"type","width":"10","filter" : true,"export":true},          
          {"dhide":true,"type":"db","title":"Sub Type","tbody":"subtype","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"Software","tbody":"software","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"S/W Version","tbody":"swVersion","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"x_pid","tbody":"x_pid","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"x_info","tbody":"x_info","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"remarks","tbody":"remarks","width":"10","filter" : true,"export":true},
          {"dhide":true,"type":"db","title":"msg","tbody":"msg","width":"10","filter" : true,"export":true},
          
          
        ],
      },


    

}